checkbox
js-tasks-ru/htmlcss-20220919_lexxminer pull request #17
Opened 2022-10-14 12:02 UTC by shomn1koff

2022-10-14 12:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-14 13:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-16 21:39 UTC, GSemikozov requested changes

2022-10-16 21:39 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +  margin-bottom: 16px;
на уровне блока марджины не задаем

2022-10-16 21:39 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +  position: absolute;
размеры не обнулены, получается что мы не прячем нативный инпут

2022-10-20 08:16 UTC, GSemikozov approved these changes

2022-10-20 08:17 UTC, merged