Radio
js-tasks-ru/htmlcss-20220919_lexxminer pull request #18
Opened 2022-10-14 13:22 UTC by shomn1koff

2022-10-14 13:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-16 21:39 UTC, GSemikozov requested changes

2022-10-16 21:39 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radio {
см комменты по чекбоксу

2022-10-20 08:17 UTC, GSemikozov approved these changes

2022-10-20 08:17 UTC, merged