я устал, босс
js-tasks-ru/htmlcss-20220919_lexxminer pull request #6
Opened 2022-09-30 15:18 UTC by shomn1koff

Герман, у меня от css уже мозг плывет, я в колонках устанавливал ширину в процентах, так вот, с высотой контейнера 50пх минимальная высота колонки будет не 0.5пх, а гораааздо больше и типа колонки условно от 1% до 10% будут иметь одинаковую высоту

2022-09-30 15:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-30 15:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-01 07:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-01 08:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-02 19:39 UTC, GSemikozov requested changes

2022-10-02 19:39 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 15px 23px 23px;
сверху 16, слева - 24

2022-10-02 19:39 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
лишнее

2022-10-05 06:27 UTC, GSemikozov approved these changes

2022-10-05 06:37 UTC, merged